LOAD DATA LOCAL INFILE '/var/www/html/students_22/Group_F/species.csv' 
INTO TABLE Species
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(SPCD, COMMON_NAME, GENUS, SPECIES, VARIETY, SUBSPECIES, SPECIES_SYMBOL);

LOAD DATA LOCAL INFILE '/var/www/html/students_22/Group_F/tree_table.csv' 
INTO TABLE Tree
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(TREE, CN, SPCD, DIA, HT, TPA_UNADJ, TPAMORT_UNADJ, 
TPAREMV_UNADJ, TPAGROW_UNADJ, CCLCD, UNCRCD,CPOSCD,CLIGHTCD,
CVIGORCD, CDENCD, CDIEBKCD, CREATED_DATE, MODIFIED_DATE);

LOAD DATA LOCAL INFILE '/var/www/html/students_22/Group_F/location.csv' 
INTO TABLE Location
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(STATECD, INVYR, UNITCD, COUNTYCD, PLOT, SUBP, TREEID);

LOAD DATA LOCAL INFILE '/var/www/html/students_22/Group_F/biomass.csv' 
INTO TABLE Biomass
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(DRYBIO_BOLE , DRYBIO_TOP,DRYBIO_STUMP, DRYBIO_SAPLING, 
DRYBIO_WDLD_SPP, DRYBIO_BG, CARBON_AG, CARBON_BG, TREEID);

LOAD DATA LOCAL INFILE '/var/www/html/students_22/Group_F/growth.csv' 
INTO TABLE Growth
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(GROWCFGS, GROWBFSL, GROWCFAL, DIA_BEGIN, DIA_MIDPT, 
DIA_END, ANN_DIA_GROWTH, HT_BEGIN, HT_MIDPT, HT_END, ANN_HT_GROWTH, TREEID);

LOAD DATA LOCAL INFILE '/var/www/html/students_22/Group_F/mortality.csv' 
INTO TABLE Mortality
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(MORTCFGS, MORTBFSL,MORTCFAL,AGENTCD, TREEID);

LOAD DATA LOCAL INFILE '/var/www/html/students_22/Group_F/damage.csv' 
INTO TABLE Damage
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(DAMLOC1,DAMTYP1, DAMSEV1,DAMLOC2 ,DAMTYP2,DAMSEV2, DECAYCD, TREEID);